### ISSUE TITLE
Gyre panics on interfaces with no addresses

### ISSUE THREAD

**Issue by narayandesai** [zeromq/gyre#19]
Gyre panics the full application on start() when run on interfaces without any addresses. 

beacon/beacon.go:138 assumes that iface.Addrs() returns a non-empty array. If this is not true, the application panics.

**Comment by armen** [comment]
Thanks for reporting the bug, sorry for my delay on responding.
Fixed the bug could you please confirm that it fixed the bug, if so please also close the issue.

**Comment by armen** [comment]
Closing the issue.
