### ISSUE TITLE
Application panic, when network restart

### ISSUE THREAD

**Issue by stephan57160** [zeromq/gyre#45]
Hi,

I tried a few things with this implementation, and found some panic.
Personally, from a library ... panic() are not so welcome ... 
so, started to investigate and found the following scenario:

1) start my application, compiled with GYRE.
2) restart network (systemctl restart network).
--> Application is stopped with a panic like "UDP impossible to send from XXX:xxx to YYY:yyy".
(sorry, I don't have the exact message anymore, but very easy to reproduce).

After investigation, I came to remove one of the "panic" and all works well.
Pull request to follow soon (in case ...).

Saw also few other "panic()" in the code, but did not check if reached or not.
Anyway, hope this helps.

**Comment by armen** [comment]
@stephan57160 The pull request is merged. Thanks for your contribution.
