### ISSUE TITLE
Discoverability in Kubernetes Pods

### ISSUE THREAD

**Issue by agerlach** [zeromq/gyre#47]
This really isn't an issue, but more of a question. Sorry if it is inappropriate here, I didn't know of a better place to ask. 

Has anybody tried deploying something like your chat docker container in Kubernetes? I can run the chat example fine locally on my laptop. It also works fine in Kubernetes if I run multiple containers in a single pod. However, if I try to more each container into its own pod they no longer can discover each other. 

Thanks for your time.

**Comment by fiatjaf** [comment]
Try somewhere on StackExchange.

**Comment by tokarthik** [comment]
@agerlach did you manage to find a solution for this issue
